### Create Article
POST http://localhost:8080/articleType
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYxODI5NzUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyNjkzNzUsImlzcyI6Ikt1blV6VGVzdCJ9.fvH5IlrR9GkiKil1MU1uzmBjpxGYbNrQtFSB7n5eaXkuqXc15aWB-xFkEAg7ZYcgccrDStsYcjThrgv0IiXpUA

{
  "orderNumber": 5,
  "name_uz": "AAAAAAAAA",
  "name_ru": "Фот",
  "name_en": "Photo"
}

### Update By Id
PUT http://localhost:8080/articleType/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYxODI5NzUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyNjkzNzUsImlzcyI6Ikt1blV6VGVzdCJ9.fvH5IlrR9GkiKil1MU1uzmBjpxGYbNrQtFSB7n5eaXkuqXc15aWB-xFkEAg7ZYcgccrDStsYcjThrgv0IiXpUA

{
  "orderNumber": 6,
  "name_uz": "Biznes",
  "name_ru": "Бизнес",
  "name_en": "Business"
}

### Delete by Id
DELETE http://localhost:8080/articleType/7
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYxODI5NzUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyNjkzNzUsImlzcyI6Ikt1blV6VGVzdCJ9.fvH5IlrR9GkiKil1MU1uzmBjpxGYbNrQtFSB7n5eaXkuqXc15aWB-xFkEAg7ZYcgccrDStsYcjThrgv0IiXpUA


### Get All //pagination
GET http://localhost:8080/articleType

### Get By lang
GET http://localhost:8080/articleType/lang?lang=en