### Create Category
POST http://localhost:8080/category/adm
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NDIwOTAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1Mjg0OTAsImlzcyI6Ikt1blV6VGVzdCJ9.YtZGny7NYZkUrQD4Jid5Cq2Be2MF7p-enCz3jHAWbMes5riSWbNXGwG2nxZQbaYPxZ9V7lhnWQIJvROmcYG7Yw

{
  "orderNumber": 3,
  "name_uz": "IQTISODIYOT",
  "name_ru": "ЭКОНОМИКА",
  "name_en": "ECONOMY"
}

### Update Category
PUT http://localhost:8080/category/adm/3
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjU4NTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTIyNTksImlzcyI6Ikt1blV6VGVzdCJ9.aa2BA6OxiXwUeYtuKVBZZH7AscdWpJIbGm8uJ3ZLZEg_3dMU27xXnpuyZIud6OnNVsJ0u6mO-KS9RKCR72oZTw

{
  "name_uz": "IQTISODIYOT",
  "name_ru": "ЭКОНОМИКА",
  "name_en": "ECONOMY"
}

### Delete By Id
DELETE http://localhost:8080/category/adm/3
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjU4NTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTIyNTksImlzcyI6Ikt1blV6VGVzdCJ9.aa2BA6OxiXwUeYtuKVBZZH7AscdWpJIbGm8uJ3ZLZEg_3dMU27xXnpuyZIud6OnNVsJ0u6mO-KS9RKCR72oZTw


### Get All
GET http://localhost:8080/category/adm
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjU4NTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTIyNTksImlzcyI6Ikt1blV6VGVzdCJ9.aa2BA6OxiXwUeYtuKVBZZH7AscdWpJIbGm8uJ3ZLZEg_3dMU27xXnpuyZIud6OnNVsJ0u6mO-KS9RKCR72oZTw


### Get By lang
GET http://localhost:8080/category/lang?lang=EN