### Create Profile (Admin)
POST http://localhost:8080/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc2MzY0ODUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc3MjI4ODUsImlzcyI6Ikt1blV6VGVzdCJ9.Rr_DSspmS7QN7oiomEiI7T-lKURjI0GhVtLnwosCU30KnAkeyo0HG3eLHyfsBsI3yG59KN9SNXA0sxilfynBWw

{
  "name": "bb",
  "surname": "aa",
  "email": "bass@gmail.com",
  "phone": "+998932222222",
  "password": "alish",
  "status": "ACTIVE",
  "role": "MODERATOR"
}

### Update Profile (Admin)
PUT http://localhost:8080/profile/adm/8
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjU4NTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTIyNTksImlzcyI6Ikt1blV6VGVzdCJ9.aa2BA6OxiXwUeYtuKVBZZH7AscdWpJIbGm8uJ3ZLZEg_3dMU27xXnpuyZIud6OnNVsJ0u6mO-KS9RKCR72oZTw

{
  "name": "Ganisher",
  "surname": "Mardonov",
  "email": "galisher@gmail.com"
}

### Update Profile
PUT http://localhost:8080/profile/admDetail
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjU4NTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTIyNTksImlzcyI6Ikt1blV6VGVzdCJ9.aa2BA6OxiXwUeYtuKVBZZH7AscdWpJIbGm8uJ3ZLZEg_3dMU27xXnpuyZIud6OnNVsJ0u6mO-KS9RKCR72oZTw

{
  "name": "Rashid",
  "surname": "Aliyev"
}

### Delete By Id (Admin)
DELETE http://localhost:8080/profile/adm/10
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjU4NTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTIyNTksImlzcyI6Ikt1blV6VGVzdCJ9.aa2BA6OxiXwUeYtuKVBZZH7AscdWpJIbGm8uJ3ZLZEg_3dMU27xXnpuyZIud6OnNVsJ0u6mO-KS9RKCR72oZTw


### Get List (Admin)
GET http://localhost:8080/profile/adm
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODA0MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc0NjY4MjYsImlzcyI6Ikt1blV6VGVzdCJ9.Ik3R12Pj5ENpSgmmVsJqb6clZTT6BJB7uZi90g_TGeGUPVzpweNsrltzTcrTkrn5r_-l1d5-6wIFg-AybS_GSA
### Update photo (Admin)
